### ISSUE TITLE
License

### ISSUE THREAD

**Issue by BrycensRanch** [ianlancetaylor/cgosymbolizer#22]
Hi, I was packaging my application that pulls in this dependency for debugging cgo stacktraces. While doing so, I got an error saying that the license this project uses is "Unknown / Other" after further digging, I saw your BSD 3-Clause License. Now checking the commit message for the `LICENSE` file, it says you *copied* code from GCC, a GPLv3'd codebase. Like the GPL v2, GPL 3 is a strong copyleft license, meaning that any copy or modification of the original code must also be released under the GPL v3. For now, I've marked this project as what you say the license is, BSD 3-Clause but it should be GPLv3. According to your other repository which you use in cgosymbolizer, you've acknowledged this issue. https://github.com/ianlancetaylor/libbacktrace/issues/31#issuecomment-575792060 Perhaps it'd be worthwhile to change the LICENSE file to reflect that.

**Comment by ianlancetaylor** [comment]
Thanks for the note.  The code in this package that is copied from GCC is all under the BSD license, not the GPL license.  Not all code in GCC is under GPLv3.  You can see that there is a license in each file; none of those licenses are GPL.

**Comment by BrycensRanch** [comment]
Ah ok, have a good day!
