### ISSUE TITLE
Bug in backtrace_pcinfo's callback function in symbolizer.c

### ISSUE THREAD

**Issue by occia** [ianlancetaylor/cgosymbolizer#5]
I think [here](https://github.com/ianlancetaylor/cgosymbolizer/blob/master/symbolizer.c#L60) should be:

    	for (pp = (struct cgoSymbolizerMore**)(&arg->data); *pp != NULL; pp = &(*pp)->more) {
	      }

The condition should be `!=` not `==`, or we will execute `pp = &(NULL)->more` definitely. Is this a typo or   I misunderstand this?

**Comment by ianlancetaylor** [comment]
Thanks.  Fixed.
