### ISSUE TITLE
How to see the c error stack trace?

### ISSUE THREAD

**Issue by JoHNNyB92** [ianlancetaylor/cgosymbolizer#7]
Hello,
We tried the proposed way of using this c to go symbolizer as mentioned here https://github.com/ianlancetaylor/cgosymbolizer/issues/6 by using it in a docker container . The application crashes ,the go error stack trace dissapears,the c error stack trace is not printed,neither i can see a new file with any kind of logs. 

How do I manage to see the c stack trace along with the c and go stack trace ?

Thanks a lot for your time and your great work and contribution.

**Comment by ianlancetaylor** [comment]
I'm sorry it doesn't work for you, but I don't know what the problem is.  I might be able to fix it if you tell me how to reproduce the problem myself: tell me exactly what you did and exactly what happened.  Note that this package is completely unsupported.
